In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("C:\\Users\\Khin\\Downloads\\ttb_dataset\\datascience.csv")

In [3]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  deposit    45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [6]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [7]:
df.shape

(45211, 17)

In [8]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may       261         1     -1         0  unknown      no  
1  unknown    5   may       151         1     -1         0  unknown      no  
2  unknown    5   may        76         1     -1         0  unknown      no  
3  unknown    5   may        92         1     -1         0  unknown      no  
4  unknown    5   may       198         1     -1         0  unknown      no

In [9]:
df.tail()

age           job   marital  education default  balance housing loan  \
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome  \
45206   cellular   17   nov       977         3     -1         0  unknown   
45207   cellular   17   nov       456         2     -1         0  unknown   
45208   cellular   17   nov      1127         5    184         3  success   
45209  telephone   17   nov       508         4     -1         0  unknown   
45210   cellular   17   nov       361         2    188        11    other   

      deposit  
45206     yes  
45207     yes  
45208     yes  
45209      no  
45210      no

In [10]:
df['age'].unique()

array([58, 44, 33, 47, 35, 28, 42, 43, 41, 29, 53, 57, 51, 45, 60, 56, 32,
       25, 40, 39, 52, 46, 36, 49, 59, 37, 50, 54, 55, 48, 24, 38, 31, 30,
       27, 34, 23, 26, 61, 22, 21, 20, 66, 62, 83, 75, 67, 70, 65, 68, 64,
       69, 72, 71, 19, 76, 85, 63, 90, 82, 73, 74, 78, 80, 94, 79, 77, 86,
       95, 81, 18, 89, 84, 87, 92, 93, 88], dtype=int64)

In [11]:
df['job'].unique()

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

In [12]:
df['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [13]:
df['education'].unique()

array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object)

In [14]:
df['default'].unique()

array(['no', 'yes'], dtype=object)

In [15]:
df['housing'].unique()

array(['yes', 'no'], dtype=object)

In [16]:
df['loan'].unique()

array(['no', 'yes'], dtype=object)

In [17]:
df['contact'].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [18]:
df['month'].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [19]:
df['poutcome'].unique()

array(['unknown', 'failure', 'other', 'success'], dtype=object)

In [20]:
df['deposit'].unique()

array(['no', 'yes'], dtype=object)

In [21]:
check_poutcome = df['campaign'] > df['previous']
status = df.loc[check_poutcome,'poutcome']
status = status[status == 'failure']
print(status)

24326    failure
24405    failure
24412    failure
24425    failure
24566    failure
          ...   
45019    failure
45022    failure
45023    failure
45106    failure
45151    failure
Name: poutcome, Length: 1141, dtype: object


In [22]:
check_poutcome = (df['poutcome'] == 'failure') &(df['deposit'] == 'no')
status = df.loc[check_poutcome]

print(status)


       age           job   marital  education default  balance housing loan  \
24060   33        admin.   married   tertiary      no      882      no   no   
24127   51        admin.    single  secondary      no     3132      no   no   
24151   33    unemployed  divorced  secondary      no     1005     yes   no   
24170   30    management    single   tertiary      no     1243     yes   no   
24184   44  entrepreneur   married   tertiary      no     1631     yes   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45180   66       retired   married  secondary      no     3409      no   no   
45181   46   blue-collar   married  secondary      no     6879      no   no   
45186   59       unknown   married    unknown      no     1500      no   no   
45189   25      services    single  secondary      no      199      no   no   
45194   59    management   married   tertiary      no      138     yes  yes   

         contact  day month  duration  campaign  pd

In [23]:
df['campaign'].unique()

array([ 1,  2,  3,  5,  4,  6,  7,  8,  9, 10, 11, 12, 13, 19, 14, 24, 16,
       32, 18, 22, 15, 17, 25, 21, 43, 51, 63, 41, 26, 28, 55, 50, 38, 23,
       20, 29, 31, 37, 30, 46, 27, 58, 33, 35, 34, 36, 39, 44],
      dtype=int64)

In [24]:
no_cust_bought_deposit = (df['deposit'] == 'yes').sum()
print(no_cust_bought_deposit)

5289


In [25]:
no_total_cust = df['deposit'].count()
print(no_total_cust)

45211


In [26]:
Conversion_Rate = no_cust_bought_deposit / no_total_cust
print(Conversion_Rate.round(2)) 
print(round(Conversion_Rate * 100, 2), "%")

0.12
11.7 %


In [27]:
df['pdays'].unique()

array([ -1, 151, 166,  91,  86, 143, 147,  89, 140, 176, 101, 174, 170,
       167, 195, 165, 129, 188, 196, 172, 118, 119, 104, 171, 117, 164,
       132, 131, 123, 159, 186, 111, 115, 116, 173, 178, 110, 152,  96,
       103, 150, 175, 193, 181, 185, 154, 145, 138, 126, 180, 109, 158,
       168,  97, 182, 127, 130, 194, 125, 105, 102,  26, 179,  28, 183,
       155, 112, 120, 137, 124, 187, 190, 113, 162, 134, 169, 189,   8,
       144, 191, 184, 177,   5,  99, 133,  93,  92,  10, 100, 156, 198,
       106, 153, 146, 128,   7, 121, 160, 107,  90,  27, 197, 136, 139,
       122, 157, 149, 135,  30, 114,  98, 192, 163,  34,  95, 141,  31,
       199,  94, 108,  29, 268, 247, 253, 226, 244, 239, 245, 204, 231,
       238, 258, 230, 254, 265,  71, 223, 246, 250, 266, 240, 205, 261,
       259, 241, 260, 234, 251, 225, 161, 237, 262, 248, 255, 220, 227,
       206, 224, 249, 235, 228, 263,   2, 270, 232, 252, 207, 200, 269,
       233, 256, 273, 272, 242, 264, 208, 214, 222, 271, 203, 22

In [28]:
df['loan_num'] = df['loan'].replace({'yes': 1, 'no': 0})
df['housing_num'] = df['housing'].replace({'yes': 1, 'no': 0})
df['default_num'] = df['default'].replace({'yes': 1, 'no': 0})

In [29]:
df['education_num'] = df['education'].map({
    'primary': 0,
    'secondary': 1,
    'tertiary': 2,
    'unknown': -1    
})
df['marital_num'] = df['marital'].map({
    'married': 0,
    'divorced': 1,
    'single': 2
})



In [30]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day  ... campaign  pdays  previous  poutcome  deposit loan_num  \
0  unknown    5  ...        1     -1         0   unknown       no        0   
1  unknown    5  ...        1     -1         0   unknown       no        0   
2  unknown    5  ...        1     -1         0   unknown       no        1   
3  unknown    5  ...        1     -1         0   unknown       no        0   
4  unknown    5  ...        1     -1         0   unknown       no        0   

  housing_num  default_num  education_num  marital_num  
0           1            0              2            0  
1           1            0              1            2  
2           1            0              1            0  
3           1            0             -1            0  
4           0            0             -1            2  

[5 rows x 22 columns]

In [31]:
# X for predictor features  
X = df[['age', 'balance', 'loan_num', 'housing_num', 'default_num', 'education_num', 'marital_num']]
X.head(3)

age  balance  loan_num  housing_num  default_num  education_num  \
0   58     2143         0            1            0              2   
1   44       29         0            1            0              1   
2   33        2         1            1            0              1   

   marital_num  
0            0  
1            2  
2            0

In [32]:
# Y for Target feature
y = df['deposit']
y.head(3)

0    no
1    no
2    no
Name: deposit, dtype: object

In [33]:
#import package
from sklearn.model_selection import train_test_split

In [34]:
# Using function "train-test_split()"
# Seperate dataset into 4 set: X_train, X_test, y_train and y_test
# test_size = 0.3 is mean seperate dataset into 70% for training and 30% for testing

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, shuffle=False)

In [35]:
X_train.head(2)

age  balance  loan_num  housing_num  default_num  education_num  \
0   58     2143         0            1            0              2   
1   44       29         0            1            0              1   

   marital_num  
0            0  
1            2

In [36]:
X_test.head(2)

age  balance  loan_num  housing_num  default_num  education_num  \
31647   77        0         0            0            0              2   
31648   33     1101         0            1            0              1   

       marital_num  
31647            0  
31648            0

In [37]:
y_train.head(2)

0    no
1    no
Name: deposit, dtype: object

In [38]:
y_test.head(2)

31647    no
31648    no
Name: deposit, dtype: object

In [39]:
# import the class function RandomForest
from sklearn.ensemble import RandomForestClassifier

In [40]:
#instantiate the model(using default parameter)
model = RandomForestClassifier()

#fit the model with data
model.fit(X_train, y_train)

RandomForestClassifier()

In [41]:
#test prediction
y_predicted = model.predict(X_test)

#Import scikit_learn metrics module for accuracy calculation
from sklearn.metrics import accuracy_score

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_predicted))

Accuracy: 0.736582129165438


In [42]:
import pandas as pd

# Create a DataFrame for the new data point
new_client = pd.DataFrame({
    'age': [45],
    'balance': [5000],
    'loan_num': [1],
    'housing_num': [0],
    'default_num': [0],
    'education_num': [2],
    'marital_num': [0],
})

# Make the prediction
prediction = model.predict(new_client)

print(prediction)

['no']
